name: Auto-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setting up environment
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y build-essential nodejs
          sudo snap install go --classic

      - name: Clone the latest AdGuardHome master branch and replace qlog.go
        run: |
          git clone https://github.com/AdguardTeam/AdGuardHome.git
          sudo yes | cp qlog.go ./AdGuardHome/internal/querylog/

      - name: Compiling binary for linux arm64
        working-directory: ./AdGuardHome
        run: |
          go mod tidy
          make init
          env GOOS='linux' GOARCH='arm64' make
          sudo mv ./AdGuardHome ./AdGuardHome-arm64-linux
          sudo mv ./AdGuardHome-arm64-linux ..

      - name: Compiling binary for linux amd64
        working-directory: ./AdGuardHome
        run: |
          go mod tidy
          make init
          env GOOS='linux' GOARCH='amd64' make
          sudo mv ./AdGuardHome ./AdGuardHome-amd64-linux
          sudo mv ./AdGuardHome-amd64-linux ..

      - name:
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a set of commands using the runners shell
      - name: Uploading binaries to GitHub Releases
        uses: softprops/action-gh-release@v2
        make_latest: "true"
        with:
          files: |
            AdGuardHome-amd64-linux
            AdGuardHome-arm64-linux
